package:
  name: sabre
  version: "1.0.0"

source:
  path: ..

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - networkx
    - numpy
    - scipy
    - matplotlib
    - samtools
    - tabix
    - bedtools
    - rich

about:
  home: https://github.com/boxiangliulab/Faser-scRNA
  license: MIT
  summary: Sabre - Single-cell reAd-Backed umi-awaRE phasing
